# Generated by Django 5.0.7 on 2024-07-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
