# Generated by Django 5.0.7 on 2024-07-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productomodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomodel',
            name='categoriaId',
        ),
        migrations.RemoveField(
            model_name='productomodel',
            name='image',
        ),
        migrations.AddField(
            model_name='productomodel',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='img_url_full',
            field=models.URLField(blank=True, null=True),
        ),
    ]
